### ISSUE TITLE
`Failed to retrieve server certificate` when on windows with linux containers

### ISSUE THREAD

**Issue by davidzwa** [Azure/event-grid-iot-edge#1]
Im trying to run the basic example from https://docs.microsoft.com/en-us/azure/event-grid/edge/pub-sub-events-webhook-local#deploy-azure-function-iot-edge-module where I want to test the event grid on a Windows docker Desktop setup with Linux containers.
When I try the same deployment on a Raspberry Pi or Azure VM, the event-grid container runs just fine. So this might be a networking issue on Windows 18363 with docker Desktop. Hopefully still, you might be able to help me.

The eventgridmodule container is correctly spawned by the edgeAgent, it is correctly bridged to the network and shows the following environment settings in Kitematic:
<pre>
"inbound:clientAuth:clientCert:enabled=false",
"inbound:serverAuth:tlsPolicy=enabled",
"outbound:webhook:httpsOnly=false"
</pre>

The error in the container is as follows:
<pre>
Unhandled Exception: System.InvalidOperationException: Failed to retrieve identity certificate from IoTEdge security daemon. StatusCode=NotFound ReasonPhrase='Not Found' ResponsePayload='' Request={"expiration":"2019-12-13T13:57:15.0109698Z"} This=SecurityDaemonClient{"moduleId":"eventgridmodule","deviceId":"--PRIVATE-DEVICE-NAME--",--PRIVATE-IOT-HUB--,"moduleGenerationId":"637112228996039004","gatewayHostName":"--PRIVATE-HOSTNAME--","workloadUri":"http://10.0.75.1:15581/","workloadApiVersion":"2019-01-30"}
   at Microsoft.Azure.EventGridEdge.IotEdge.SecurityDaemonClient.GetIdentityCertificateAsync(TimeSpan validity, CancellationToken token) in /home/vsts/work/1/s/tools/SecurityDaemonClient/SecurityDaemonClient.cs:line 181
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.IoTEdgeEnvironment.ConfigureOutgoingClientAuthAsync() in /home/vsts/work/1/s/src/IoTEdgeHost/IoTEdgeEnvironment.cs:line 100
   at Microsoft.Azure.EventGridEdge.Common.BaseEnvironment.SetupOutboundClientAuthAsync() in /home/vsts/work/1/s/src/Common/BaseEnvironment.cs:line 245
   at Microsoft.Azure.EventGridEdge.Common.BaseEnvironment.InitializeAsync(AuthOptions authOptions) in /home/vsts/work/1/s/src/Common/BaseEnvironment.cs:line 68
   at Microsoft.Azure.EventGridEdge.CoreHost.EventGridCoreHost.InitializeAsync(JObject settings, JObject authSettings) in /home/vsts/work/1/s/src/Core.Host/EventGridCoreHost.cs:line 110
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.StartAsync() in /home/vsts/work/1/s/src/IoTEdgeHost/Program.cs:line 119
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.Main() in /home/vsts/work/1/s/src/IoTEdgeHost/Program.cs:line 48
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.<Main>()
</pre>

@VidyaKukke Any idea what might be causing this? I can provide more details if needed, no problem.

**Comment by VidyaKukke** [comment]
Hi David,

To make sure I understand, you are using docker on windows and bringing up event grid module?
I have tried on Windows machines in Azure (where the VM is an edge device) without any issues so might be a local setup.

From the call stack you shared, the event grid module seems to getting an error when talking to the IoTEdge security daemon. It does this to configure its certificate for outgoing calls.

To help you further, we will need security daemon logs. 
1. Follow the steps outlined https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot and retrieve security daemon logs.  
2. Restart the eventgridmodule so that it attempts to retrieve the certificate again and you should see  logs related to that in security daemon.
3. Run the following command 'docker container inspect eventgridmodule' and share the output.

I will probably need the help from IoT Edge team after this to root cause.

Thanks

**Comment by davidzwa** [comment]
I found out that my docker desktop was not binding the port to host, but the the azure-iot-edge bridged network.

I dont completely understand why binding to the host worked (0.0.0.0 instead of internal docker network), since it should only require the bridge).

Will get back if you still need more details, because this is still a problem albeit fixed by a work-around.

**Comment by davidzwa** [comment]
@VidyaKukke The actual reason is (probably) edge-module related, not event-grid-edge SDK related and easily fixed on Windows. Still I wonder why it occurs. 

- Is a bridge good enough?
- Does the module need to connection to the host (iotedge daemon) or to the edgeAgent?

Thanks for your time.

**Comment by davidzwa** [comment]
I see the 404 coming back in the daemon logs, as the eventgridmodule does get an answer.
<pre>
12/9/2019 3:25:47 PM info: edgelet_http::logging -- [work] - - - [2019-12-09 14:25:47.830983200 UTC] "POST
                     //modules/eventgridmodule/genid/637112228996039004/certificate/server?api-version=2019-01-30
                     HTTP/1.1" 404 Not Found - "-" "-" auth_id(-)
</pre>

The whole output:
<pre>
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Get-IoTEdgeLog

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Initialize-IoTEdge, Insta...



TimeCreated          Message
-----------          -------
12/9/2019 3:25:47 PM info: edgelet_http::logging -- [work] - - - [2019-12-09 14:25:47.147359300 UTC] "POST
                     /modules/eventgridmodule/genid/637112228996039004/sign?api-version=2018-06-28 HTTP/1.1" 200 OK 57
                     "-" "-" auth_id(-)
12/9/2019 3:25:47 PM info: edgelet_http::logging -- [work] - - - [2019-12-09 14:25:47.830983200 UTC] "POST
                     //modules/eventgridmodule/genid/637112228996039004/certificate/server?api-version=2019-01-30
                     HTTP/1.1" 404 Not Found - "-" "-" auth_id(-)
12/9/2019 3:25:50 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:25:50.861489700 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:25:56 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:25:56.049450 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:01 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:01.119156400 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:06 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:06.188816900 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:11 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:11.260206400 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:16 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:16.336797100 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:21 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:21.413716600 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:26 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:26.484681400 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:31 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:31.559461700 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:33 PM info: edgelet_core::watchdog -- Checking edge runtime status
12/9/2019 3:26:33 PM info: edgelet_core::watchdog -- Edge runtime is running.
12/9/2019 3:26:36 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:36.611354 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:41 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:41.652654600 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:46 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:46.726213200 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:51 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:51.798183500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:26:56 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:26:56.848352200 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:01 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:01.906101900 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:06 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:06.972061800 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:12 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:12.014066 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:17 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:17.085134 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:22 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:22.163137900 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:27 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:27.240860500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:32 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:32.297162600 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:33 PM info: edgelet_core::watchdog -- Checking edge runtime status
12/9/2019 3:27:33 PM info: edgelet_core::watchdog -- Edge runtime is running.
12/9/2019 3:27:37 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:37.326738700 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:42 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:42.356108900 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:47 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:47.414296800 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:52 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:52.495270 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:27:57 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:27:57.567378800 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:02 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:02.620077100 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:07 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:07.699244600 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:12 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:12.778414200 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:17 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:17.837023500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:22 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:22.890008300 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:27 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:27.976915500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:33 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:33.014056300 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:33 PM info: edgelet_core::watchdog -- Checking edge runtime status
12/9/2019 3:28:33 PM info: edgelet_core::watchdog -- Edge runtime is running.
12/9/2019 3:28:38 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:38.073843 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:43 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:43.133310900 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:48 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:48.182048 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:53 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:53.246872 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:28:58 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:28:58.317001400 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:03 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:03.376274300 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:08 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:08.428999800 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:13 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:13.502888600 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:18 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:18.566743500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:23 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:23.638382500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:28 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:28.697998500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:33 PM info: edgelet_core::watchdog -- Checking edge runtime status
12/9/2019 3:29:33 PM info: edgelet_core::watchdog -- Edge runtime is running.
12/9/2019 3:29:33 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:33.767262900 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:39 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:39.352132800 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:44 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:44.461732600 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:49 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:49.547991500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:54 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:54.623760600 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:29:59 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:29:59.693680300 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:30:04 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:30:04.759616300 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:30:09 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:30:09.816277400 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:30:14 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:30:14.860340100 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:30:19 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:30:19.914472900 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:30:24 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:30:24.951906500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:30:30 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:30:30.023897100 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:30:33 PM info: edgelet_core::watchdog -- Checking edge runtime status
12/9/2019 3:30:33 PM info: edgelet_core::watchdog -- Edge runtime is running.
12/9/2019 3:30:35 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:30:35.344194500 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:30:40 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:30:40.461438900 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
12/9/2019 3:30:45 PM info: edgelet_http::logging -- [mgmt] - - - [2019-12-09 14:30:45.529382 UTC] "GET
                     /modules?api-version=2019-01-30 HTTP/1.1" 200 OK 3957 "-" "-" auth_id(-)
</pre>

The **eventgridmodule** on the same moment, logs the following constantly:
<pre>
****************************************************************************************************************************
|  _______                                   __________                      _____       _________        _____ _________  |
|  ___    |__________  _______________       ___  ____/___   _______ _______ __  /_      __  ____/___________(_)______  /  |
|  __  /| |___  /_  / / /__  ___/_  _ \      __  __/   __ | / /_  _ \__  __ \_  __/      _  / __  __  ___/__  / _  __  /   |
|  _  ___ |__  /_/ /_/ / _  /    /  __/      _  /___   __ |/ / /  __/_  / / // /_        / /_/ /  _  /    _  /  / /_/ /    |
|  /_/  |_|_____/\__,_/  /_/     \___/       /_____/   _____/  \___/ /_/ /_/ \__/        \____/   /_/     /_/   \__,_/     |
|                                                                                                                          |
****************************************************************************************************************************
2019-12-09 14:25:46.601:[INF] - [EdgeHubClient:StartAsync@64] Azure IoT Edge ModuleClient created successfully.
2019-12-09 14:25:47.461:[INF] - [EdgeHubClient:StartAsync@78] Azure IoT Edge ModuleClient opened successfully.
2019-12-09 14:25:47.812:[INF] - [BaseEnvironment:SetupInboundServerAuthAsync@110] Starting. inbound:serverAuth={
  "tlsPolicy": "Strict",
  "serverCert": {
    "source": "IoTEdge"
  }
}

Unhandled Exception: System.InvalidOperationException: Failed to retrieve server certificate from IoTEdge security daemon. StatusCode=NotFound ReasonPhrase='Not Found' ResponsePayload='' Request={"commonName":"--LEFT-OUT-FOR-PRIVACY--","expiration":"2020-03-08T14:25:47.8230032Z"} This=SecurityDaemonClient{"moduleId":"eventgridmodule","deviceId":"--LEFT-OUT-FOR-PRIVACY--","iotHubHostName":"--LEFT-OUT-FOR-PRIVACY--","moduleGenerationId":"637112228996039004","gatewayHostName":"--LEFT-OUT-FOR-PRIVACY--","workloadUri":"http://10.0.75.1:15581/","workloadApiVersion":"2019-01-30"}
   at Microsoft.Azure.EventGridEdge.IotEdge.SecurityDaemonClient.GetServerCertificateAsync(TimeSpan validity, CancellationToken token) in /home/vsts/work/1/s/tools/SecurityDaemonClient/SecurityDaemonClient.cs:line 153
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.IoTEdgeEnvironment.ConfigureServerCertificateAsync() in /home/vsts/work/1/s/src/IoTEdgeHost/IoTEdgeEnvironment.cs:line 65
   at Microsoft.Azure.EventGridEdge.Common.BaseEnvironment.SetupInboundServerAuthAsync() in /home/vsts/work/1/s/src/Common/BaseEnvironment.cs:line 155
   at Microsoft.Azure.EventGridEdge.Common.BaseEnvironment.InitializeAsync(AuthOptions authOptions) in /home/vsts/work/1/s/src/Common/BaseEnvironment.cs:line 60
   at Microsoft.Azure.EventGridEdge.CoreHost.EventGridCoreHost.InitializeAsync(JObject settings, JObject authSettings) in /home/vsts/work/1/s/src/Core.Host/EventGridCoreHost.cs:line 110
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.StartAsync() in /home/vsts/work/1/s/src/IoTEdgeHost/Program.cs:line 119
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.Main() in /home/vsts/work/1/s/src/IoTEdgeHost/Program.cs:line 48   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.<Main>()
</pre>

**Comment by davidzwa** [comment]
Do have to add: I think I want to disable certificates, if that's easier. This is a development setup anyway, so maybe the environment settings of the client cert are not getting through? (Just guessing here)

**Comment by davidzwa** [comment]
I noticed `sign?api-version=2018-06-28` in the log. Incompatibility maybe?

Also I noticed this:
<pre>
‼ config.yaml has correct hostname - Warning
    config.yaml has hostname RGS-DZWART which does not comply with RFC 1035.

    - Hostname must be between 1 and 255 octets inclusive.
    - Each label in the hostname (component separated by ".") must be between 1 and 63 octets inclusive.
    - Each label must start with an ASCII alphabet character (a-z), end with an ASCII alphanumeric character (a-z, 0-9), and must contain only ASCII alphanumeric characters or hyphens (a-z, 0-9, "-").

    Not complying with RFC 1035 may cause errors during the TLS handshake with modules and downstream devices.

</pre>

I have a device with capital letters in its device host-name (don't ask me why, I cant change it)

**Comment by VidyaKukke** [comment]
Thanks David. This certainly looks odd. I don't believe they're related to dev certs. We'll wait for root cause from IoT Team.

Basically you will need to turn off securing "Outgoing client authentication" by setting
outbound:clientAuth:clientCert:enabled=false. Remember to make the change and redeploy. Then it will not make this call.

Doc links that is useful for this
https://docs.microsoft.com/en-us/azure/event-grid/edge/configure-event-grid
https://docs.microsoft.com/en-us/azure/event-grid/edge/configure-identity-auth

Thanks!

**Comment by davidzwa** [comment]
Let me know if you need more information. I have a fleet of devices at hand and am very willing to debug and PR if necessary (also to understand the module better and to help work on getting it out there)

**Comment by davidzwa** [comment]
I get the same error with the "outbound:clientAuth:clientCert:enabled=false" environment setting.

Are you sure `Env` is the right way to name the section? Where can I find the code which is running the EventGrid Module? I need to know what runs behind it to help.

Edit: I did see the environment variables reflected in the container with `printenv`.

**Comment by VidyaKukke** [comment]
Hi David,

I did reach out to IoT team and unfortunately they are saying the setup you are trying is unsupported per https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fiot-edge%2Fsupport%23operating-systems&data=02%7C01%7Cvkukke%40microsoft.com%7C5b9b1a05d5e843ffb9ff08d77cd6677a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637115132604179834&sdata=QJxvBECZqlw92PS67LNH12XI3KH05q5C5G%2F3NR8ZCnA%3D&reserved=0 so they don't plan to look into it.

> I get the same error with the "outbound:clientAuth:clientCert:enabled=false" environment setting.
> Are you sure Env is the right way to name the section? Where can I find the code which is running the EventGrid Module? I need to know what runs behind it to help.
> Edit: I did see the environment variables reflected in the container with printenv.

Yes. Looking closely at the newly pasted logs it seems like a servercert issue as well. First it was identity and then server cert. Basically all forms of communication with Security Daemon is failing. Period. So you can turn off all security like serverauth, clientauth inbound and outbound. 

1. inbound:serverAuth:tlsPolicy=disabled
2. outbound:clientAuth:clientCert:enabled=false
3. outbound:webhook:skipServerCertValidation=true

I would like to work with you offline and then update this thread after. My alias is vkukkeatmicrosoft.

**Comment by davidzwa** [comment]
Setup deemed to fail on the Windows side of things. Makes sense therefore closing.

To the future reader: advice is definitely to avoid Windows+ linux docker, since there's a lot of possible things which can go wrong (trust me, I tried a lot)
