### ISSUE TITLE
Quickstart without azure function

### ISSUE THREAD

**Issue by davidzwa** [Azure/event-grid-iot-edge#4]
Please provide a quick-start with a normal deployment template and the modules in the form factor which Azure Edge templates provide them:

- deployment.template.json
- modules / subscriber / module.json
- modules / subscriber / subscriber.csproj (+simplest possible c# code)
- modules / subscriber / amd64.Dockerfile
- modules / publisher / module.json
- modules / publisher / publisher.csproj (+simplest possible c# code)
- modules / publisher / amd64.Dockerfile
- config / deployment.amd64.json

As vscode provides new users with a template, so it really is a *quick-start*

**Comment by VidyaKukke** [comment]
Thank you for the suggestion. The idea for quickstarts was to keep them simple enough to help customers starting new. If a non-azure function based subscriber module is desired please use the gitHub samples for reference. There is no plan to make complex subscriber modules as part of quickstarts.
