### ISSUE TITLE
SSL cant be disabled, tlsPolicy:disabled doesnt seem to be the fix

### ISSUE THREAD

**Issue by davidzwa** [Azure/event-grid-iot-edge#6]
`outbound:serverAuth:tlsPolicy:disabled` or any of the flavors given by the author do not result in HTTP on 5558 nor 4438 to setup a useful connection.

Both 4438 and 5558 result in being unusable using the following eventgridmodule deployment config:
<pre>
"Env": [
                  "outbound:clientAuth:clientCert:enabled=false",
                  "outbound:serverAuth:tlsPolicy=disabled",
                  "inbound:serverAuth:tlsPolicy=disabled",
                  "inbound:clientAuth:clientCert:enabled=false"
                ],
                "HostConfig": {
                  "PortBindings": {
                    "4438/tcp": [
                      {
                        "HostPort": "4438"
                      }
                    ],
                    "5888/tcp": [
                      {
                        "HostPort": "5888"
                      }
                    ]
                  }
                }
</pre>

**Comment by VidyaKukke** [comment]
This will control whether you want HTTP/HTTPs only:

inbound:serverAuth:tlsPolicy=disabled -> Only HTTP
inbound:serverAuth:tlsPolicy=enabled -> Both HTTP/HTTPs
inbound:serverAuth:tlsPolicy=strict      -> Only HTTPs

HTTP is served on Port 5888
HTTPs is served on Port 4438
If you want access using either of these protocols from the host machine/outside you will need to do host mapping in addition to setting up the flag.

Reference: [Event Grid Configuration](https://docs.microsoft.com/en-us/azure/event-grid/edge/configure-event-grid) about turning off.
