### ISSUE TITLE
Module still in Preview

### ISSUE THREAD

**Issue by davidzwa** [Azure/event-grid-iot-edge#7]
What is the roadmap of this module? Why is it not being developed when there clearly is a full documentation on it's use in production-type environment? (Security-wise)

**Comment by jfggdl** [comment]
@davidzwa, thanks for your questions. Event Grid on IoT Edge will remain in preview for at least this year. Please reach out to us in January 2021 and I should be able to give you a more precise timeline. By the way, we are indeed actively investing on the next version of Event Grid to support more edge scenarios and that is why we have an extended preview time.

**Comment by davidzwa** [comment]
Good to hear, this solution is great for IoT Edge when developers need devices to communicate in the on-premise environment (instead of just D2C or C2D). At the time I was working with it, it seemed like the only viable option to set up such messaging with event-grid.

Will be looking forward to it in 2021. Maybe it is also nice to think about auto-discovery options without having to use UDP/mDNS or DNS, since this has become a great obstruction in my experience as well. I see a lot of potential in event-grid-iot-edge to be able to provide a solution for this 'cross-device' problem. I also understand if this is entirely not the purpose of it however.

**Comment by jfggdl** [comment]
@davidzwa, thanks for your interest and suggestions. Would you be able to meet with us to understand your requirements so that we can consider those as potential features?

**Comment by davidzwa** [comment]
That is ok with me, as long as your colleague (VidyaKukke) is ok with it, looking at our past communication mishap. At the time I was very eager to help understand this module **for an internship**, but got very little information from him about the module's source code and thus had to leave the preview behind. So, as might be clear, there is no commercial interest from my side, purely a hobby/exploration interest.

The following problems were vital to why this module was not useful to preview:
- Inside simulator, the module didnt work (possibly fixable by [issue](https://github.com/Azure/event-grid-iot-edge/issues/10))
- Running on Windows with Linux containers wasnt supported, not related to the module, but still essential for previewing.
- Running on Rasp. Pi 4 with self-signed certificates or even skipping SSL didnt work at the time.

So, as you see, it was quite impossible to get even a physical edge device to work with this, although one would prefer to run it on their laptop to start with. That's a major deal-breaker for using the module: developing with it is impossible if you have to run a deployment with your new code payload everytime you need to make a change.

**Comment by bkarrlander** [comment]
Are there any updates on the roadmap of this module? Is GA in the works? We are looking at using it in a production environment.

**Comment by VidyaKukke** [comment]
> Are there any updates on the roadmap of this module? Is GA in the works? We are looking at using it in a production environment.

Thank you for the interest. We did not see much traction for this offering and am afraid we could not justify the investment any longer which means there are no GA plans for this. We however do have a https://docs.microsoft.com/en-us/azure/event-grid/kubernetes/ offering and would be happy to engage and connect if this matches your requirement.

Let us know.

Thanks,
Vidya
