### ISSUE TITLE
Question: Why is it needed to open inbound port 4438

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/event-grid-iot-edge#8]
Why is [documented](https://docs.microsoft.com/en-us/azure/event-grid/edge/forward-events-iothub) that I have to open an **inbound port 4438**? 

Opening inbound ports in an IoT Edge scenario is from a security standpoint not recommended and in most cases [not needed](https://github.com/Azure/iotedge/blob/master/doc/networking.md).

Or is this only needed when I use  "an Azure VM as an edge device"?

**Comment by VidyaKukke** [comment]
You are correct. Opening ports is not needed unless you want to communicate from outside or even from the host machine (like an Azure VM). For the typical cases where publishers are other IoT edge  modules on the same edge device there is no need to open  ports.
We can clarify this statement in our docs in our next refresh.  Thank you.

**Comment by sandervandevelde** [comment]
Thanks. The same text is also shown in other related examples regarding Event Grid on Edge.

**Comment by VidyaKukke** [comment]
Understood. We will make that clarification. Thank you.
